services:
  nginx:
    image: nginx
    build: nginx
    ports:
      - 80:80
    container_name: hw0
  mongo:
    image: mongo
    build: mongo
    ports:
      - 27017:27017
    container_name: hw2
  portainer:
    image: portainer/portainer-ce:latest
    volumes:
      - "portainer_data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - 8000:8000
      - 9443:9443

volumes:
  portainer_data:
